microformats/mf2py

requirements.txt, test/test_parser.py
minor tweaks to restore python3 compatibility for nosetests
=> py3 compatibility fixes in test_parser and requirements.txt

mf2py/parser.py
fixes https://github.com/kartikprabhu/mf2py/issues/53
=> fixed filter_by_type to match any possible type.

mf2py/parser.py, test/examples/rel_enclosure.html, test/test_parser.py
Also fixes alternates parsing.
See http://microformats.org/wiki/microformats2-parsing-brainstorming#more_information_for_rel-based_formats
for discussion
=> Add the rel-urls parsing for better rel handling

mf2py/parser.py, test/test_parser.py
=>  fold "value" of nested h-* e-* into parent mf object 

mf2py/parser.py, test/examples/nested_complex_values.html
see for details: http://microformats.org/wiki/microformats2-parsing-brainstorming#Nested_h-.2A_objects.27_.22value.22_property
=> nested h-* take the first "name" or "url" as "value"

mf2py/backcompat.py, mf2py/implied_properties.py, mf2py/mf2_classes.py, mf2py/parse_property.py, mf2py/parser.py, test/test_parser.py
For consistency across all properties and values.
@tommorris @kevinmarks @kartikprabhu @snarfed do y'all agree that this is a good idea?
Fixes #43
=> Convert all string literals to unicode literals

mf2py/parse_property.py, test/examples/link_with_u-url.html, test/test_parser.py
=> parse u-* properties from link elements

mf2py/backcompat.py, test/examples/backcompat_hentry_with_rel_tag.html, test/test_parser.py
rel=tag becomes p-category, using the last path segment of the tag URL
as the new category name.
Fixes #58
=> backcompat: convert rel=tag

CHANGELOG.md, mf2py/parser.py, mf2py/version.py
=> add html_parser property to specify which parser BS4 should use

mf2py/backcompat.py
22 calls to soup.find_all turned out to be very expensive, taking ~90%
of the total time spent parsing. instead we can just call it once and
collect all the classic microformats roots at once.
cc: @snarfed @KevinMarks
=> call soup.find_all only once in backcompat.apply_rules

mf2py/parse_property.py, mf2py/parser.py
Allows replacing dict with an OrderedDict, which makes testing and debugging easier,
and yields nicer output from hosted tools like mf2.kylewm.com
(e.g. http://mf2.kylewm.com/?url=https://adactio.com/notes/10610)
=> support specifying custom dict implementation

.gitignore, .travis.yml, mf2py/backcompat.py, mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/mf2_classes.py, mf2py/parse_property.py, mf2py/parser.py, mf2py/version.py, requirements.txt, test/examples/backcompat_ignore_mf1_properties_in_mf2_root.html, test/examples/backcompat_ignore_mf1_root_if_mf2_present.html, test/examples/backcompat_ignore_mf2_properties_in_mf1_root.html, test/examples/backcompat_nested_mf1_in_mf2.html, test/examples/backcompat_nested_mf1_in_mf2_e_content.html, test/examples/backcompat_nested_mf2_in_mf1.html, test/examples/backcompat_no_implied_properties_mf1_root.html, test/test_parser.py
updated with new implied name parsing rules per http://microformats.org/wiki/index.php?title=microformats2-parsing&oldid=66695 and https://github.com/microformats/microformats2-parsing/issues/6
1) bump version to 1.1.0 since it is a "major" change 
2) added tests for new implied name rules
3) modified earlier tests to accommodate new rules
=> new implied name parsing rules and better backcompat

mf2py/dom_helpers.py, mf2py/mf2_classes.py, mf2py/parse_property.py, mf2py/value_class_pattern.py
As pointed out by @kartikprabhu, there were some warning about unused code/imports. also found a function that's not being used.
=> remove dead code and unused imports

mf2py/parser.py, test/examples/parse_id.html, test/test_parser.py
Implements https://github.com/microformats/microformats2-parsing/issues/44
=> implement id parsing

test/test_parser.py
=> Specify parser to avoid warning in CI

README.md
=> Remove CanIUsePython3

.github/workflows/tests.yml
=> Switch to main in CI tests

.github/workflows/tests.yml, requirements.txt, setup.cfg, setup.py, test/test_parser.py, test/test_suite.py
=> Switch from nosetests to pytest

.github/workflows/tests.yml, requirements.txt, setup.cfg, setup.py, test/test_parser.py, test/test_suite.py
This PR includes code written by @angelogladding that transitions use of nose2 to pytest. The code was moved to a separate branch on this repository as we need to test the GitHub Action configuration against the project.
=> Move from nose2 to pytest

mf2py/__init__.py, mf2py/backcompat.py, mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py, mf2py/value_class_pattern.py, test/test_parser.py, test/test_suite.py
I have run `isort` to properly order import statements in the package.
=> Run `isort`

mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py
=> Replace `dict_class` with standard `dict`

.github/workflows/tests.yml
This PR ensures the tests GitHub Actions run on Windows and macOS.
=> Add Windows and macOS tests

.github/workflows/tests.yml
Bring poetry action up to date
=> Add 3.11, 3.12 and drop pypy from test matrix; upgrade poetry action

pyproject.toml, test/test_parser.py
Closes https://github.com/microformats/mf2py/issues/221
=> Mock is part of standard library
