microformats/mf2py

test/test_parser.py
I had removed whitespace from strings in a couple of the unit tests,
introducing a test regression. It turns out the difference was that
I had lxml installed in my virtualenv, which behaves differently
from html5lib; where html5lib preserves whitespace. since html5lib
is specified in the requirements.txt, the unit tests should follow
its behavior.
This should fix issue #27
=> restore whitespace in unit tests

mf2py/parse_property.py, test/examples/u-test.html
We were using an incorrect method for extracting the e-content "html" value.
This was originally https://github.com/tommorris/mf2py/pull/19 but I split it up into three separate PRs for easier processing. This fixes https://github.com/kartikprabhu/mf2py/issues/47
=> fix e-content for innerHTML

mf2py/backcompat.py, mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py, mf2py/temp_fixes.py
bs4.find and find_all seem to be unduly expensive operations.
just replacing them with naive get_children and get_descendants
calls cuts the *total* parse time in half for lots of documents.
Parsing kylewm.com went from around 130ms to 66ms 
(epeus.blogspot.com and chocolateandvodka.com -- backcompat
tests -- are about the same), the very large page at 
rhiaro.co.uk/travel from 780ms to 420ms
Ref #63
=> replace calls to find_all with custom traversal

mf2py/implied_properties.py, test/examples/implied_properties.html, test/examples/silopub.html, test/test_parser.py
Based on discussion in http://microformats.org/wiki/microformats2-parsing-issues#implied_name_when_alt.3D.22.22
the implied cases that expect alt or title should ignore it when it's intentionally blank.
Fixes #67
=> implied properties should ignore alt=""

mf2py/backcompat.py, mf2py/parser.py, test/test_parser.py
Wordpress has site-title and site-description on the default templates, so this will fix hfeed parsing from them at once.
Blogger has title and description, but the hfeed is often misplaced so doesn't contain them. This may be a small fix to default templates.
Example at http://www.unmung.com/mf2?url=http%3A%2F%2Fma.tt&html=&pretty=on
Shows now getting a name a summary tagline from matt's bloge, where before we had a nasty implied name.
=> Add backcompat for wordpress, blogger

.gitignore, mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py, mf2py/version.py, requirements.txt, test/test_parser.py
version 1.0.6
many bug fixes for parsing according to spec
Summary
1) strip leading/trailing white space for `e-*[html]`. update the corresponding tests
2) blank values explicitly authored are allowed as property values 
3) include `alt` or `src` from `<img>` in parsing for `p-*` and `e-*[value]`
4) parse `title` from `<link>` for `p-*` resolves #84 
5) and `poster` from `<video>` for `u-*` resolves #76 
6) use `html5lib` as default parser
7) use the final redirect URL resolves #62 
8) update requirements to use BS4 v4.6.0 and html5lib v1.0.1
=> v1.0.6 many bug fixes

.travis.yml
since html5lib dropped support for 2.6 anyway
=> drop 2.6 from tests add upto 3.6 

mf2py/parser.py, test/examples/implied_properties/stop_implied_url.html, test/test_parser.py
implied name was tracked in a bool before, I now track the types of properties encountered in a set and check for names and url, prepared for any other implied properties being restricted.
=> reduced implied urls (fixes #117), added tests

.gitignore, mf2py/dom_helpers.py, test/examples/tag_whitespace_inside_p_value.html, test/test_parser.py
fixes #112. lots of background discussion there.
largely inspired by https://wiki.zegnat.net/media/textparsing.html (but not completely; more details in #112)
this is not at all pretty, and i'm open to ideas, although i'd end up refactoring much more of `get_textContent()` in the process. it passes all mf2py and granary tests though, which counts for something.
=> whitespace handling: don't collapse whitespace between tags

mf2py/dom_helpers.py, test/examples/implied_properties/implied_name_alt.html, test/test_parser.py
...e.g. from img alt text next to a single space. (was happening with other elements too.)
cc @kartikprabhu. the PR here is just the last commit. the others will disappear as soon as #115 is approved and merged.
=> don't collapse multiple space elements in a row

mf2py/backcompat.py, mf2py/dom_helpers.py, mf2py/mf2_classes.py, mf2py/parser.py
Testing against cleverdevils massive feed, this improves the mf2-parsing stage (so excluding HTML parsing) of parsing cleverdevils large feed file by around 20 %, from ~1s to ~0.8s
The number of iterations over class lists is reduced, regular expressions are pre-compiled and combined into larger ones.
=> Performance improvements: reduce and optimize regular expressions

mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py, test/examples/broken_url.html, test/test_parser.py
Fixes #79 by passing through the values as they are, since https://github.com/microformats/microformats2-parsing/issues/9 didn't lead to any other suggestion.
=> Catch ValueError from urljoin, pass through broken value instead

mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, mf2py/parser.py, test/examples/broken_url.html, test/test_parser.py
builds on #124 
This especially improves performance on feed pages with many absolute links (e.g. almost 10% in one example), by saving a lot of unnecessary URL parsing inside `urljoin`. This path is around 50x faster for absolute URLs, and indiemap suggests the ratio of absolute to relative URLs in url-properties is roughly 1:1, so this this extra check is amortized easily.
Note that the try...except from #124 is *not* made unnecessary by this, since URLs with other protocols and protocol-relative URLs can still hit the problematic path.
=> Absolute URL shortcut around urljoin

.github/workflows/tests.yml
Unfortunately, this means temporarily dropping multi-OS testing for now. May bring back the Mac testing at some point, and if there's demand, we can start doing Windows testing again when there's a sensible way to get libxml2 on Windows in CI.
=> Update CI setup to install libxml2

CHANGELOG.md, mf2py/version.py, setup.py
Release five fixes/features along with a setup.py `python_requires` version specifier in anticipation of python2 deprecation. See https://github.com/microformats/mf2py/issues/87#issuecomment-1610297218
=> Prepare release for 1.1.3

mf2py/parser.py
This PR enables the `img_with_alt` flag by default on parser invocations.
=> Enable img_with_alt by default

.github/workflows/tests.yml, dumpout.py, pyproject.toml
This PR adds `black` and `isort` to the CI stage, allowing us to run the linting process in the CI.
=> Add linting CI actions

mf2py/implied_properties.py, test/examples/implied_properties/implied_photo_relative_url.html, test/test_parser.py
=> Resolve implied photo relative paths

mf2py/datetime_helpers.py, test/test_parser.py
Applies to VCP and standard dt- objects.
Closes #176 and spills into https://github.com/microformats/microformats2-parsing/issues/12. We are already normalizing all datetime objects so it would be awkward to implement for VCP and not dt- objects.
=> Add timezone offset normalisation

CHANGELOG.md, mf2py/parse_property.py, test/examples/relative_url_in_e.html, test/test_parser.py
Closes #181.
Does not support `srcset` -- should eventually reuse logic from https://github.com/microformats/mf2py/pull/188 when ready.
=> Make relative URLs in `e-` properties absolute

CHANGELOG.md, mf2py/dom_helpers.py, test/examples/plaintext_img_whitespace.html, test/examples/plaintext_p_whitespace.html, test/examples/value_name_whitespace.html, test/test_parser.py
A newline is added after paragraphs during plaintext conversion.
Closes #202.
=> Fix whitespace in plaintext conversion

CHANGELOG.md, mf2py/dom_helpers.py, mf2py/implied_properties.py, mf2py/parse_property.py, test/examples/img_with_srcset.html, test/examples/img_with_srcset_with_base.html, test/test_parser.py
- a source without a descriptor defaults to `1x`
- sources with already seen descriptors are ignored
- URLs may contain a comma
Closes #169.
=> Add srcset support

CHANGELOG.md, mf2py/parse_property.py, mf2py/parser.py, test/examples/language.html, test/test_parser.py
Add language details to embedded properties and root microformats using the following order of specificity:
embedded properties (class=e-* lang=..)
root microformats (class=h-* lang=..)
document root (<html lang=..>)
Closes #150.
=> Add language support

README.md, test/test_parser.py
Testing for extensions (`filter_class`, `expose_dom` and `metaformats`) requires passing extension-related arguments to `parse_fixture()`.
=> Prepare tests to test extensions

CHANGELOG.md, README.md, mf2py/parse_property.py, mf2py/parser.py, test/test_parser.py
=> Add extension to expose DOM for embedded properties
